name: Auto Rerun Failed Workflows

on:
  workflow_run:
    workflows: ["Suno Mini MVP CI/CD"]
    types: [completed]

jobs:
  rerun:
    if: github.event.workflow_run.conclusion == 'failure'
    runs-on: ubuntu-latest
    steps:
      - name: Check rerun attempts
        id: check
        run: |
          MAX_ATTEMPTS=2
          CURRENT_ATTEMPT=${{ github.event.workflow_run.run_attempt }}
          echo "max_attempts=$MAX_ATTEMPTS" >> $GITHUB_OUTPUT
          echo "current_attempt=$CURRENT_ATTEMPT" >> $GITHUB_OUTPUT
          echo "should_rerun=$([[ $CURRENT_ATTEMPT -lt $MAX_ATTEMPTS ]] && echo 'true' || echo 'false')" >> $GITHUB_OUTPUT

      - name: Rerun workflow
        if: steps.check.outputs.should_rerun == 'true'
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.event.workflow_run.id }}/rerun

      - name: Max attempts reached
        if: steps.check.outputs.should_rerun == 'false'
        run: |
          echo "Maximum rerun attempts (${{ steps.check.outputs.max_attempts }}) reached"
          echo "Manual intervention required"