name: RepairRoutine
on:
  workflow_call:
    inputs:
      component:
        required: true
        type: string

jobs:
  repair:
    runs-on: ubuntu-latest
    steps:
      - name: Run repair for ${{ inputs.component }}
        run: |
          echo "Repairing ${{ inputs.component }}"
          # add retries/fallback per componente
