name: Deploy to AWS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod
      instance_type:
        description: 'EC2 instance type'
        required: true
        default: 't3.medium'
        type: choice
        options:
        - t3.small
        - t3.medium
        - t3.large

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation deploy \
            --template-file aws-deploy.yml \
            --stack-name suno-mini-mvp-${{ inputs.environment }} \
            --parameter-overrides \
              Environment=${{ inputs.environment }} \
              InstanceType=${{ inputs.instance_type }} \
            --capabilities CAPABILITY_IAM \
            --no-fail-on-empty-changeset
            
      - name: Get stack outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name suno-mini-mvp-${{ inputs.environment }} \
            --query 'Stacks[0].Outputs' \
            --output table